repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.6"
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format
  - repo: https://github.com/PyCQA/bandit
    rev: "1.9.4"
    hooks:
      - id: bandit
        language_version: python3
        exclude: (test.*\.py|conftest\.py)$
        args:
          - -s
          - B404,B603,B310
  - repo: https://github.com/allganize/ty-pre-commit
    rev: "v0.0.23"
    hooks:
      - id: ty-check
        args: [ --python-version, "3.14" ]
        exclude: ^tests/
